apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp-deployment
  labels:
    app: java-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: java-webapp-container
        image: mar97/java-web-app:v1.0.9-31
        # imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: java-webapp-service
spec:
  selector:
    app: java-webapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: LoadBalancer
