---
- name: init server 
  hosts: localhost 
  tasks:
    - name: run docker image
      command: "docker run -p 8088:8080 -d mar97/java-web-app:v3.12.103-712"


# eksctl create cluster --name k8s-cluster \
#    --region us-east-1 \
#    --node-type t2.small \ 