---
- name: init server 
  hosts: localhost 
  tasks:
    - name: run docker image
      command: "docker run -p 8088:8080 -d mar97/java-web-app:v1.0.1-13

# sed -i 's/java-web-app:v1.0.1-13 ]*/java-web-app:v1.0.1-13 deploy.yaml