---
- name: init server 
  hosts: localhost 
  tasks:
    - name: run docker image
      command: "docker run -p 8088:8080 -d mar97/java-web-app:1.0.1-6"

# sed -i 's/java-web-app:1.0.1-6 ]*/java-web-app:1.0.1-6 deploy.yaml